version: 2

project_name: goreleaser-test

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    main: ./main.go
    binary: tfh
    ldflags:
      - -s -w
      - -X github.com/kszarek/goreleaser-test/version.version={{.Version}}
      - -X github.com/kszarek/goreleaser-test/version.commit={{.Commit}}
      - -X github.com/kszarek/goreleaser-test/version.date={{.Date}}

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github-native

release:
  github:
    owner: kszarek
    name: goreleaser-tests
  draft: false
  replace_existing_draft: false
  make_latest: true
  mode: append
  name_template: "v{{ .Version }}"
  target_commitish: "{{ .Commit }}"
  prerelease: auto
